apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acl-operator
  namespace: argocd

  finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
    - resources-finalizer.argocd.argoproj.io

  # # Since this creates and edits resources dynamically
  annotations:
    #argocd.argoproj.io/sync-options: Validate=false
    argocd.argoproj.io/sync-wave: "-9"

spec:
  project: kafka-resource-manager

  # Sync policy
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

  destination:
    server: https://kubernetes.default.svc
    namespace: confluent

  source:
    repoURL: https://github.com/trinadsz/dfp-gitops-package-kafka-topic-operator.git
    targetRevision: master
    path: implementation/acl-operator

      # Additional values.yaml go here. The one under the charts dir is picked by Argo by default
      #helm:
      #valueFiles:
    #- implementation/xxx/values.yaml
