apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acl-operator

  namespace: argocd
  annotations:
    # ArgoCD sync waves used to solve order of operations problems. Lower values sync before higher values.
    # https://argoproj.github.io/argo-cd/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kafka-resource-manager
  source:
    repoURL: https://github.com/aetna-digital-infrastructure/dfp-gitops-package-kafka-topic-operator.git
    targetRevision: feature/add_topic_and_acloperator
  #  path: packages/user-operator/modules
     path: packages/profiles/lab/acl-operator/modules
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernete