---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-acl-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-acl-operator
  template:
    metadata:
      labels:
        name: strimzi-acl-operator
    spec:
      serviceAccountName: strimzi-acl-operator
      containers:
        - name: strimzi-acl-operator
          image: dsouzat/operators:latest
          args:
            - /opt/strimzi/bin/user_operator_run.sh
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_CA_CERT_NAME
              value: my-cluster-clients-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: my-cluster-clients-ca
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: my-confluent-oss-cp-zookeeper-headless:2181
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "20000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "true"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 300
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 300
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 100m
  strategy:
    type: Recreate


